# Server Configuration
server:
  port: "8080"

# Database Configuration
database:
  host: "10.60.254.127"
  port: 3306
  user: "it"
  password: "a*999999"
  dbname: "system_hardening"

# LDAP Configuration
ldap:
  server: "ldaps://10.60.254.252:636"
  base_dn: "dc=hot,dc=local"
  domain_suffix: "hot.local"
  use_tls: true
  insecure: true
  user_filter: "(sAMAccountName=%s)"
  admin_username: "ylw@hot.local"
  admin_password: "!Qw2!Qw2!Qw2!Qw2"
  security_group_dn: "CN=IT部,OU=IT部,OU=HOT,DC=hot,DC=local"
  cert_path: "./certificate/ca.crt"

# JWT Configuration
jwt:
  secret_key: "system-hardening-platform-jwt-secret-key-2024-secure-min-32-chars"
  expiry_hour: 8

# Packages Configuration
packages:
  linux_package_dir: "./packages/linux"
  windows_package_dir: "./packages/windows"
  server_url: "http://10.60.1.191:8080" # 客户端访问的后端地址
